# https://crates.io/crates/cargo-lints

warn = [
    # https://github.com/rust-lang/rust-clippy

    "clippy::cargo",
    "clippy::nursery",
    "clippy::pedantic",

    # https://doc.rust-lang.org/rustc/lints/groups.html

    "future_incompatible",
    "nonstandard_style",
    "rust_2018_compatibility",
    "rust_2018_idioms",
    "rust_2021_compatibility",
    "unused",

    # https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#keyword-idents

    "absolute_paths_not_starting_with_crate",
    "elided_lifetimes_in_paths",
    "explicit_outlives_requirements",
    "keyword_idents",
    "macro_use_extern_crate",
    "meta_variable_misuse",
    "missing_abi",
    # "missing_copy_implementations",
    "missing_debug_implementations",
    # "missing_docs",
    "non_ascii_idents",
    "noop_method_call",
    "pointer_structural_match",
    "rust_2021_incompatible_closure_captures",
    "rust_2021_incompatible_or_patterns",
    "rust_2021_prefixes_incompatible_syntax",
    "rust_2021_prelude_collisions",
    "single_use_lifetimes",
    "trivial_casts",
    "trivial_numeric_casts",
    "unreachable_pub",
    # "unsafe_code",
    # "unsafe_op_in_unsafe_fn",
    # "unstable_features",
    "unused_crate_dependencies",
    "unused_extern_crates",
    "unused_import_braces",
    "unused_lifetimes",
    "unused_qualifications",
    # "unused_results",
    # "variant_size_differences",
]

allow = [
    "clippy::cargo_common_metadata", # TODO
    "clippy::missing_errors_doc", # TODO
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
    "clippy::redundant_pub_crate",
    "clippy::unreadable_literal",
    "clippy::use_self",
    "clippy::wildcard-imports",
]
